#!/bin/sh

mkdir -p "vault"
mkdir -p "workshop"
mkdir -p "warehouse"
mkdir -p "laboratory"
mkdir -p "delivery bay"
mkdir -p "step_01"

# these have author info available in "standard" format
ln -s "../../../incoming/vault/Cinemaware" "vault/Cinemaware"
ln -s "../../../incoming/workshop/ABK" "workshop/ABK"
ln -s "../../../incoming/workshop/NP2" "workshop/NP2"
ln -s "../../../incoming/workshop/P41A" "workshop/P41A"
ln -s "../../../incoming/workshop/P4X" "workshop/P4X"
ln -s "../../../incoming/workshop/P60" "workshop/P60"
ln -s "../../../incoming/workshop/P6X" "workshop/P6X"
ln -s "../../../incoming/workshop/PHA" "workshop/PHA"
ln -s "../../../incoming/workshop/PP21" "workshop/PP21"
ln -s "../../../incoming/workshop/PP30" "workshop/PP30"
ln -s "../../../incoming/workshop/TP3" "workshop/TP3"
ln -s "../../../incoming/workshop/channel players" "workshop/channel players"
ln -s "../../../incoming/workshop/chiptracker" "workshop/chiptracker"
ln -s "../../../incoming/workshop/prun" "workshop/prun"
# only for songlengths
ln -s "../../../incoming/vault/Sonix" "vault/Sonix"
ln -s "../../../incoming/vault/TFMX merged" "vault/TFMX merged"
ln -s "../../../incoming/vault/TFMX single sample set" "vault/TFMX single sample set"
ln -s "../../../incoming/workshop/NP1" "workshop/NP1"
ln -s "../../../incoming/workshop/NP3" "workshop/NP3"
ln -s "../../../incoming/workshop/P40A" "workshop/P40A"
ln -s "../../../incoming/workshop/P40B" "workshop/P40B"
ln -s "../../../incoming/workshop/P60a" "workshop/P60a"
ln -s "../../../incoming/workshop/P61" "workshop/P61"
ln -s "../../../incoming/workshop/P61A" "workshop/P61A"
ln -s "../../../incoming/workshop/PM01" "workshop/PM01"
ln -s "../../../incoming/workshop/PP10" "workshop/PP10"
ln -s "../../../incoming/workshop/PP20" "workshop/PP20"
ln -s "../../../incoming/workshop/PPK" "workshop/PPK"
ln -s "../../../incoming/workshop/PRU1" "workshop/PRU1"
ln -s "../../../incoming/workshop/PRU2" "workshop/PRU2"
ln -s "../../../incoming/workshop/SKYT" "workshop/SKYT"
ln -s "../../../incoming/workshop/STPK" "workshop/STPK"
ln -s "../../../incoming/workshop/TP1" "workshop/TP1"
ln -s "../../../incoming/workshop/TP2" "workshop/TP2"
ln -s "../../../incoming/workshop/UNIC" "workshop/UNIC"
ln -s "../../../incoming/workshop/UNIC2" "workshop/UNIC2"
ln -s "../../../incoming/workshop/XANN" "workshop/XANN"
ln -s "../../../incoming/workshop/ZEN" "workshop/ZEN"
ln -s "../../../incoming/workshop/eureka packer" "workshop/eureka packer"
ln -s "../../../incoming/workshop/fc-m" "workshop/fc-m"
ln -s "../../../incoming/workshop/fuzzac packer" "workshop/fuzzac packer"
ln -s "../../../incoming/workshop/heatseeker" "workshop/heatseeker"
ln -s "../../../incoming/workshop/hornet packer" "workshop/hornet packer"
ln -s "../../../incoming/workshop/icetracker" "workshop/icetracker"
ln -s "../../../incoming/workshop/kefrens sound machine" "workshop/kefrens sound machine"
ln -s "../../../incoming/workshop/kris tracker" "workshop/kris tracker"
ln -s "../../../incoming/workshop/laxity tracker" "workshop/laxity tracker"
ln -s "../../../incoming/workshop/promizer" "workshop/promizer"
ln -s "../../../incoming/workshop/propacker" "workshop/propacker"
ln -s "../../../incoming/workshop/skyt packer" "workshop/skyt packer"
ln -s "../../../incoming/workshop/unic tracker" "workshop/unic tracker"
ln -s "../../../incoming/workshop/xann packer" "workshop/xann packer"
ln -s "../../../incoming/laboratory/Martin Bazley tracker" "laboratory/Martin Bazley tracker"
ln -s "../../../incoming/laboratory/Quartet_ST_(4q)" "laboratory/Quartet_ST_(4q)"
ln -s "../../../incoming/laboratory/Quartet ST without smp-files" "laboratory/Quartet ST without smp-files"
ln -s "../../../incoming/laboratory/SUNTronicTunes" "laboratory/SUNTronicTunes"
ln -s "../../../incoming/laboratory/Sierra AGI" "laboratory/Sierra AGI"
ln -s "../../../incoming/laboratory/TCB Tracker" "laboratory/TCB Tracker"
# misc
ln -s "../../../incoming/laboratory/unsorted gamemusic" "laboratory/unsorted gamemusic"
ln -s "../../../incoming/laboratory/various_formats_from_amiga_games" "laboratory/various_formats_from_amiga_games"
ln -s "../../../incoming/warehouse/IT" "warehouse/IT"
ln -s "../../../incoming/warehouse/MOD" "warehouse/MOD"
ln -s "../../../incoming/warehouse/S3M" "warehouse/S3M"
ln -s "../../../incoming/warehouse/XM" "warehouse/XM"
ln -s "../../../incoming/delivery bay/2022-09-27-from_EpicTyphlosion" "delivery bay/2022-09-27-from_EpicTyphlosion"
ln -s "../../../incoming/delivery bay/Amiga game mods" "delivery bay/Amiga game mods"
ln -s "../../../incoming/delivery bay/croy" "delivery bay/croy"
ln -s "../../../incoming/delivery bay/from_Chip" "delivery bay/from_Chip"
ln -s "../../../incoming/delivery bay/lemmings_music_mod" "delivery bay/lemmings_music_mod"
ln -s "../../../incoming/delivery bay/mbnet_mods" "delivery bay/mbnet_mods"
ln -s "../../../incoming/delivery bay/mod_jp" "delivery bay/mod_jp"
ln -s "../../../incoming/delivery bay/noise" "delivery bay/noise"
ln -s "../../../incoming/delivery bay/principium" "delivery bay/principium"
ln -s "../../../incoming/delivery bay/various" "delivery bay/various"
ln -s "../../../incoming/step_01/mbnet_mods" "step_01/mbnet_mods"
# no support ?
ln -s "../../../incoming/workshop/TP6" "workshop/TP6"
ln -s "../../../incoming/workshop/HCD" "workshop/HCD"
ln -s "../../../incoming/workshop/NTP1" "workshop/NTP1"
ln -s "../../../incoming/workshop/NewtronPacker" "workshop/NewtronPacker"
ln -s "../../../incoming/workshop/P22A" "workshop/P22A"
ln -s "../../../incoming/workshop/P30A" "workshop/P30A"
ln -s "../../../incoming/workshop/P60-packedsamples" "workshop/P60-packedsamples"
ln -s "../../../incoming/workshop/PR10" "workshop/PR10"
ln -s "../../../incoming/workshop/PR20" "workshop/PR20"
ln -s "../../../incoming/workshop/PR40" "workshop/PR40"
ln -s "../../../incoming/workshop/moduleprotector" "workshop/moduleprotector"
ln -s "../../../incoming/workshop/startrekkerpacker" "workshop/startrekkerpacker"
ln -s "../../../incoming/laboratory/FLAME" "laboratory/FLAME"
ln -s "../../../incoming/laboratory/MP" "laboratory/MP"
